<?php
include_once('init.php');
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Skillsapien.com - Terms of Use</title>
<link href="css/style.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="outer">
<div id="men">
    <?php echo $get_template->process('global_header1.php')?>

  <div class="canten" >
    <div class="center_in" style="overflow:scroll;  height:600px; width:96%;">
      <div class="center_left">
        <h1>Terms Of Use</h1>
        <h2>General Definitions</h2>
        <h2></h2>
        <p>This User Agreement is effective as of November 1, 2011. Your continued use of the Skillsapien.com website after this time signifies your acceptance of this User Agreement.</p>
        <p>Welcome to Skillsapien.com, the website and online service of Skillsapien Pty Ltd, (collectively “Skillsapien”, “we”, or “us”). This page explains the terms by which you may use our web site, web widgets, feeds, mobile software applications, applications for third-party web sites and services, and any other web services or applications owned, controlled, or offered by Skillsapien (collectively the “Site”). By accessing or using the Site you signify that you have read, understood, and agree to be bound by the following User Agreement (“User Agreement” or this “Agreement”), which includes and hereby incorporates by reference the agreements and policies referenced in this User Agreement, or linked from the following URL:</p>
        <p><a href="#">http://www.Skillsapien.com/termofuse.html</a> (collectively the “Terms of Service”).</p>
        <p>We reserve the right to revise this User Agreement and the Terms of Service and all linked information from time to time in our sole discretion by updating this posting or any linked information. We may make such revisions without prior notice to you, so please check back often for updates. Unless otherwise provided in such revision, the revised User Agreement or Terms of Service, or part thereof, will take effect when they are posted.</p>
        <h2>Site Services</h2>
        <p>Skillsapien is an online exchange for the trading of futures availability of skilled professionals. The site allows recruiters with job requirements to bid for current or future availability of suitably qualified skilled professionals, anywhere in the world.  Candidates can visualize their relative competitiveness in any given market, industry or skillset against their peers and manage bids to achieve the highest market value possible. Recruiters can also effectively plan and budget for the future, knowing that supply of the most critically needed skills can be locked in simply through simply bidding for the right profiles on Skillsapien.</p>
        <h1>For Candidates</h1>
         <h2>Key Offerings include:</h2>
         <ul>
         <li><p>Ability to enter multiple Skill Profiles per candidate, allowing a multi-faceted way for candidates to present themselves and have complete freedom to work with the Profile that can achieve the maximum market value</p></li>
         <li><p>Manage availability and rates to optimize market demand</p></li>
         <li><p>Receive automated alerts for relevant bids and (keyword-matched) job opportunities posted by recruiters</p></li>
         <li><p>Feature video/audio intros to further entice recruiters</p></li>
         <li><p>Ability to broadcast Skillsapien updates to all connections on social media networks such as Facebook and LinkedIn</p></li>
         <li><p>Ability to port existing account/profile info from social networking sites such as LinkedIn</p></li>
         <li><p>Extensive keywords-based Jobs and Skills searching</p></li>
         </ul>
         <h2>Key Obligations:</h2>
         <ul>
         <li><p>Present their Skill Profiles, experiences and availability in a truthful manner.</p></li>
         <li><p>Abide by Skillsapien anonymity requirements and not to disclose any personal contact information where required not to do so</p></li>
         <li><p>Respond to all bids with sincerity and truthful intentions.</p></li>
         <li><p>Acceptance of a bid indicates commitment to perform the job pending Interview outcomes</p></li>
         <li><p>Once interview process completed, truthfully disclose to Skillsapien the final outcome and whether a resulting Job Offer/Placement has occurred.</p></li>
         <li><p>Not to solicit recruiters outside of Skillsapien and its processes for any engagement or dialogue with a recruiter initiated or facilitated via Skillsapien.</p></li>
         <li><p>Provide any post-job reviews or rating truthfully and in a respectable manner  (This is a two-way process)</p></li>
         <li><p>Failure to adhere to the above may result in a review of the Candidate’s user account. Skillsapien reserves the right to terminate any account usage at our sole discretion.</p></li>
         <li><p>Candidates are solely responsible for satisfying their own income tax, payroll tax, payroll withholding, governmental reporting and any other legal requirements under the relevant applicable law. Skillsapien maintains no obligation to report any nominal bid earnings through Skillsapien, nor will we disclose this information to anyone without the explicit agreement from the Candidate.</p></li>
         </ul>
         <h1>For Recruiters</h1>
         <h2>Key Offerings:</h2>
         <ul>
         <li><p>Ability to conduct detailed searches based on Keyword and/or skill-tree matches</p></li>
         <li><p>Ability to bid on suitably qualified candidate Skill Profiles, now or in the future</p></li>
         <li><p>Ability to purchase for Interview Rights on suitable candidates</p></li>
         <li><p>Ability to close the recruitment/placement transaction all through Skillsapien – resulting in less admin and overheads</p></li>
         <li><p>Ability to purchase Skillsapien Credits for transactional purposes – simpler and more consistent than trying to deal with a myriad different transaction amounts that may fluctuate due to currency movements</p></li>
         <li><p>Ability to enter regular, recurring monthly subscriptions which offers significant value-add over once-off purchases of Skillsapien Credits</p></li>
         <li><p>Able to provide and read feedbacks on candidate job performance – resulting in greater insight. (Note: this process is two-way to ensure equal opportunity on both sides)</p></li>
         </ul>
         <h2>Key Obligations:</h2>
         <ul>
         <li><p>Agree for Skillsapien to charge a fee (in Credits) for the right to Interview a candidate for a particular job or job opportunity. Once accepted and the relevant fee (in Credits) deducted, Skillsapien will releasepersonal contact information for the candidate concerned so that the Interview can take place.</p></li>
         <li><p>Truthfully disclose all final outcome of candidate interviews to Skillsapien in a timely manner.</p></li>
         <li><p>Agree for Skillsapien to charge a fee (in Credits) for any eventual Placement resulting from a successful Interview or Interviews. Where Credits balance falls short of the required amount for Placement, agree for Skillsapien to invoice monetarily to replenish the Credits back up to the required level.</p></li>
         <li><p>By continuing to use Site services you agree not to take any action directly or indirectly to circumvent the above-mentioned fees.</p></li>
         <li><p>Not to retain any personal contact information of candidates concerned past the interview or placement process, as this information remains the exclusive property of Skillsapien.</p></li>
         <li><p>Advertise or post genuine job opportunities with genuine intention to pay the advertised rates.</p></li>
         <li><p>Failure to adhere to the above may result in a review of the Recruiter’s user account. Skillsapien reserves the right to terminate any account usage at our sole discretion.</p> </li>
         </ul>
         <h2>Relationship between Recruiters and Candidates</h2>
        <p>The contracting and fulfilment of a Job is strictly between theRecruiter and Candidate. A Placement transaction on Skillsapien indicates the Recruiter’s agreement to pay, and the Candidate’s agreement to deliver, the prescribed services, however this does not constitute a Warranty or Guarantee in any form by Skillsapien that these services will be delivered. Subsequent performance of the service and payment are the responsibility of the two parties and should be covered by binding contract between the parties.</p>
        <p>Any modification to the rates, terms, or nature of service after a Placement transaction has occurred is outside the service scope of Skillsapien and must be dealt with between the Recruiter and Candidate. It is worth noting that, through the Skillsapien feedback system, dishonest conduct or unprofessional behaviour will likely be reflected accordingly and may affect the party’s future standing and credibility in subsequent transactions.</p>
        <p>Where disputes occur over job feedbacks, Skillsapien will do its best to arbitrate and resolve the matter to a mutually satisfactory outcome. However if necessary Skillsapien reserves the right to refer the matter to the appropriate legal and/or industrial tribunals in the relevant jurisdictions.</p>
        <h2>Relationship with Skillsapien</h2>
        <p>Skillsapien is not a party to the dealing, contracting and fulfilment of a Job between a Recruiter and a Candidate, including the Candidate Services. Skillsapien has no control over and does not guarantee the quality, safety or legality of Candidate Services advertised, the truth or accuracy of Job listings, the qualifications, background, or abilities of member users, the ability of Candidates to deliver services, the ability of Recruiters to pay for Candidate Services, or that a Recruiter or Candidate can or will actually complete a transaction.</p>
        <p>Skillsapien is not required to and does not verify any information given to us by Candidates, nor does Skillsapien perform background checks on Candidates. If any transaction are to take place, all parties agree to conduct this on the basis of good faith and professional integrity, reinforced through the feedback and reputation system available through Skillsapien.</p>
        <p>Where necessary, however, Skillsapien may provide information about a Recruiter or Candidate, such as detailed feedback or past transactional behaviour, or third party validations or certifications provided to us by the Recruiter or Candidate. Such information is provided on a discretionary basis solely as a value-add service and does not constitute an endorsement or recommendation either way by Skillsapien.</p>
        <p>All rights and obligations for the purchase of Candidate Services are solely between the Recruiter and Candidate and both parties must look solely to the other for enforcement and performance of all the rights and obligations arising from Member Contracts and any other terms, conditions, representations, or warranties associated with such dealings.</p>
        <h2>Third-Party Beneficiary of Member Contract</h2>
        <p>Recruiters and Candidates must both acknowledge and agree that the value, reputation, and goodwill of the Site depend on their performance of their covenants and agreements as set forth in their Member Contract. Recruiter and Candidate therefore appoint Skillsapien a third-party beneficiary of their Member Contract for purposes of enforcing the obligations owed to, and the benefits conferred on, Skillsapien by this Agreement. Recruiters and Candidates further agree that Skillsapien has the right to take such actions with respect to the Member Contract or their Accounts, including without limitation suspension, termination, or legal actions, as Skillsapien in its sole discretion deems necessary to protect the value, reputation, and goodwill of the Site.</p>
        <p>This Agreement and any registration for or subsequent use of this Site will not be construed as creating or implying any relationship of agency, franchise, partnership or joint venture between you and Skillsapien, except and solely to the extent expressly stated.</p>
        <h2>Member Eligibility and Financial Obligations</h2>
        <p>To access Site Services through our Site, you must be a legal entity, or an individual in business 18 years or older who can form legally binding contracts.</p>
        <p>To register for an Account with Skillsapien and become a Member, you must accept all of the terms and conditions in, and linked to, this Agreement.</p>
        <p>By becoming a Member, you agree to:</p>
        <p>(a) Abide by this Agreement and the processes, procedures, and guidelines described throughout the Site;</p>
        <p>(b)	Be financially responsible for your use of the Site and the purchase or delivery of expected Services; and</p>
        <p>(c)	Perform your obligations as specified by any Member Contract that you accept, unless such obligations are prohibited by law or by this Agreement.</p>
        <p>d)	Once an interview has been completed you will advise Skillsapien truthfully of the interview outcome. If it leads into an Job Offer or Placement you will duly abide to pay (either in Credits or in real world Currency) the outstanding Placement Fee invoiced to you at the time.</p>
        <p>Skillsapien reserves the right in its sole discretion to refuse, suspend, or terminate service to anyone for any reason or no reason.</p>
        <h2>Account Usage</h2>
        <p>To become a Member and access Site Services through our Site you must register for an "Account.” You agree to provide true, accurate and complete information as prompted by the registration form and all forms you access on the Site, and to update this information to maintain its truthfulness, accuracy and completeness.</p>
        <p>If registering as a legal entity (rather than an individual), you may grant certain account administration privileges to one or more “Account Administrators” with consultation from. Any or all Accounts related to a legal entity may be suspended or terminated without warning if the legal entity is found to be in breach of any Terms under this Agreement.</p>
        <p>Members represents, warrants, and agrees to grant access to the Account only to Users authorised to act on behalf of the Member and only in accordance with this Agreement. Additionally, Member represents, warrants, and agrees to be fully responsible and liable for any action of any User who uses the Account, and any related Account. You agree (1) not to use any Account, username, or password of another User of the Site that you are not authorised to use, and (2) not to allow others who are not authorised to do so to use the Account or any related Team Account at any time.</p>
        <p>Your Skillsapien Account (including feedback) and username are not transferable, and any transfer or attempted transfer to another party is null and void.</p>
        <h2>Usernames and Password</h2>
        <p>When a Member registers an Account, the Member will be asked to choose a username and password for the Account.</p>
        <p>As a Member, you agree and you are entirely responsible to safeguard and maintain the confidentiality of the username and password you use to access this Site. In all cases, you authorise Skillsapien to assume that any person using the Site with your username and password either is you or is authorised to act for you. You agree to notify us immediately if you suspect or become aware of any unauthorised use ofthe Account or access to your password or the password of any User of your Account.</p>
        <h2>Directory of Candidates</h2>
        <p>The Site contains a directory of Candidates. The directory is populated with information from third-party sources, from Candidates themselves, and from other Members. Skillsapien provides this directory as a convenience and does not confirm or verify the information contained in it.</p>
        <h2>Verification and Monitoring</h2>
        <p>Skillsapienmay, from time to time, make available to Members various third party services for verifying a Member’s credentials, provide testing services, or provide third-party information. Any opinions, advice, statements, services, offers or other information or content expressed or made available by these third parties or any other Members are those of the respective author(s) or distributor(s) and not of Skillsapien. Skillsapien neither endorses nor is responsible for the accuracy or reliability of any opinion, advice, information or statement made on the Site by anyone other than authorised Skillsapien employees acting in their official capacities.</p>
        <h2>Links</h2>
        <p>This Site may contain links to third party Web sites, services, or resources. Such Web sites, services, and resources are owned and operated by the third-parties and/or their licensors. Your access and use of those Web sites, services, and/or resources, including online communication services such as chat, email and calls, will be governed by the terms and policies of the applicable Web site, service, or resource or Candidate. You acknowledge and agree that Skillsapien is not responsible or liable for: (i) the availability or accuracy of such sites, services, or resources; or (ii) the content, advertising, or products on or available from such sites, services, or resources. The inclusion of any link on the Site does not imply that we endorse the linked site. You use the links and these services at your own risk.</p>
        <h2>Licenses and Site Access</h2>
        <p>The Site contains robot exclusion headers. You agree that you will not use any robot, spider, scraper or other automated means to access the Site for any purpose without our express written permission.</p>
        <p>Additionally, you agree that you will not:</p>
        <p>(a) Take any action that imposes or may impose (in our sole discretion) an unreasonable or disproportionately large load on our infrastructure;</p>
        <p>(b) Copy, reproduce, modify, create derivative works from, distribute, or publicly display any content (other than content you have submitted to the Site) from the Site, any software code that is part of the Site, or any services that are
offered on the Site without the prior express written permission of Skillsapien and the appropriate third party, as applicable;</p>
        <p>(c) Interfere or attempt to interfere with the proper operation of the Site or any activities
conducted on the Site;</p>
        <p>(d) Bypass any measures we may use to prevent or restrict access to the Site or any subparts of the Site including without limitation features that prevent or restrict use or copying of any content or enforce limitations on use of the Site or the content therein;</p>
        <p>(e) Transmit spam, chain letters, or other unsolicited communications;</p>
        <p>(f) Attempt to interfere with, compromise the system integrity or security or decipher any transmissions to or from the servers running the Site;</p>
        <p>(g) Upload invalid data, viruses, worms, or other software agents through or to the Site;</p>
        <p>(h) Collect or harvest any personally identifiable information, including account names, from the Site;</p>
        <p>(i) Access any content on the Service through any technology or means other than those provided or authorised by the Service; or</p>
        <p>(j) Directly or indirectly, advertise or promote another website, product, or service or to solicit other Users for other websites, products or services.</p>
        <p>Accessing the audio-visual content available on the Site for any purpose or in any manner other than defined below is expressly prohibited. Audio-visual data uploaded by Skillsapien users are typically provided to help other users to make more informed decisions about them (e.g. bidding or not bidding) and should be treated as copyright material of that user. Unless specified otherwise by the originating user, this data is not intended to be copied, stored, permanently downloaded, orredistributed by any users.</p>
        <h2>User Content</h2>
        <p>Some areas of the Site may allow Users to post feedback, comments, questions, and other information (“User Content”). You are solely responsible for your User Content that you upload, publish, display, link to or otherwise make available (hereinafter, “post”) through the Site, and you agree that we are only acting as a passive conduit for your online distribution and publication of your User Content. You understand that whether or not such User Content is published, Skillsapien does not guarantee any confidentiality with respect to any User Content.</p>
        <p>You agree not to post User Content that:</p>
        <p>(i)	May create a risk of harm, loss, physical or mental injury, emotional distress, death, disability, disfigurement, or physical or mental illness to you, to any other person, or to any animal;</p>
        <p>(ii)	May create a risk of any other loss or damage to any person or property;</p>
        <p>(iii)	Seeks to harm or exploit children by exposing them to inappropriate content, asking for personally identifiable details or otherwise;</p>
        <p>(iv)	May constitute or contribute to a crime or tort;</p>
        <p>(v)	Contains any information or content that we deem to be unlawful, harmful, abusive, racially or ethnically offensive, defamatory, infringing, invasive of personal privacy or publicity rights, harassing, humiliating to other people (publicly or otherwise), threatening, profane, or otherwise objectionable;</p>
        <p>(vi)	Contains any information or content that is illegal (including, without limitation, the disclosure of insider information under securities law or of another party’s trade secrets);</p>
        <p>(vii)	Contains any information or content that you do not have a right to make available under any law or under contractual or fiduciary relationships; or</p>
        <p>(viii)	Contains any information or content that you know is not correct and current. You agree that any User Content that you post does not and will not violate third-party rights of any kind, including without limitation any Intellectual Property Rights, rights of publicity and privacy. To the extent that your User Content contains music or video, you hereby represent that you are the owner of all the copyright rights, including without limitation the performance, mechanical, and sound recordings rights, with respect to each and every musical composition (including lyrics) and sound recording contained in such User Content and have the power to grant the license granted below. You understand that publishing your User Content on the Service is not a substitute for registering it with the relevant Copyright Offices of your jurisdiction or any other rights organisation.</p>
        <p>Skillsapien takes no responsibility and assumes no liability for any User Content that you or any other User or third party posts or sends over the Service. You understand and agree that any loss or damage of any kind that occurs as a result of the use of any User Content that you send, upload, download, stream, post, transmit, display, or otherwise make available or access through your use of the Service, is solely your responsibility. Skillsapien is not responsible for any public display or misuse of your User Content. You understand and acknowledge that you may be exposed to User Content that is inaccurate, offensive, indecent, objectionable, or inappropriate for children, and you agree that Skillsapien shall not be liable for any damages you allege to incur as a result of such User Content.</p>
        <p>Furthermore, Skillsapien has no editorial control over User Content posted by Users on the Site and is not responsible for and does not monitor such content for accuracy or reliability. Skillsapien does not confirm or verify whether a Candidate has the expertise, or is qualified or licensed to provide the Candidate Services or advice being requested.You further agree not to post any User Content that contains any requests for or information enabling contact or payment outside of the Site.</p>
        <p>Skillsapien reserves the right, but is not obligated, to reject and/or remove any User Content that Skillsapien believes, in its sole discretion, violates these provisions.</p>
        <h2>User License to Skillsapien</h2>
        <p>You retain all your ownership rights in your User Content. By posting any User Content on the Site, you expressly grant, and you represent and warrant that you have a right to grant, to Skillsapien a royalty-free, sub-licensable, transferable, perpetual, irrevocable, non-exclusive, worldwide license to use, reproduce, modify, publish, list information regarding, edit, translate, distribute, publicly perform, publicly display, and make derivative works of all such User Content and your name, voice, and/or likeness as contained in your User Content, in whole or in part, and in any form, media or technology, whether now known or hereafter developed, for use in connection with the Site and Skillsapien’s (and its successors’ and affiliates’) business, including without limitation for promoting and redistributing part or all of the Site (and derivative works thereof) in any media formats and through any media channels. Notwithstanding the foregoing, Skillsapien will only use or disclose your User Content posted to non-public areas of the Site to the extent necessary to provide you the services on the Site. You also hereby grant each User of the Site a non-exclusive license to access your User Content through the Site, and to use, reproduce, distribute,display and perform such User Content as permitted through the functionality of the Site and under this Agreement.</p>
        <p>The above licenses granted by you in your User Content terminate within a commercially reasonable time after you remove or delete your User Content from the Site. You understand and agree, however, that Skillsapien may retain, but not display, distribute, or perform, server copies of User Content that have been removed or deleted. The above licenses granted by you in User Content for which the Site does not provide you a means to delete or remove are perpetual and irrevocable.</p>
        <p>You may choose to or we may invite you to submit comments or ideas about the Site, including without limitation about how to improve the Site or our products (“Ideas”). By submitting any Idea, you agree that your disclosure is gratuitous, unsolicited and without restriction and will not place Skillsapien under any fiduciary or other obligation, and that we are free to use the Idea without any additional compensation to you, and/or to disclose the Idea on a non-confidential basis or otherwise to anyone. You further acknowledge that, by acceptance of your submission, Skillsapien does not waive any rights to use similar or related ideas previously known to Skillsapien, or developed by its employees, or obtained from sources other than you.</p>
        <h2>Additional User Representations and Warranties</h2>
        <p>You shall be solely responsible for your own User Content and the consequences of posting or publishing it. In connection with your User Content, you affirm, represent and warrant, in addition to the other representations and warranties in this Agreement, the following:</p>
        <p>a.	You are at least 18 years of age or a legal entity and are fully able and competent to enter into the terms, conditions, obligations, affirmations, representations, and warranties set forth in this Agreement, and to abide by and comply with this Agreement. </p>
        <p>b.	You have the written consent of each and every identifiable natural person in the User Content to use such person’s name or likeness in the manner contemplated by the Site and this Agreement, and each such person has released you from any liability that may arise in relation to such use. </p>
        <p>c.	Your User Content and Skillsapien’s use thereof as contemplated by this Agreement and the Site will not infringe any rights of any third party, including but not limited to any Intellectual Property Rights, privacy rights and rights of publicity. </p>
        <p>d.	Skillsapien may exercise the rights to your User Content granted under this Agreement without liability for payment of any guild fees, residuals, payments, fees, or royalties payable under any collective bargaining agreement or otherwise. </p>
        <h2>Skillsapien License to User</h2>
        <p>Subject to and conditioned on compliance with this Agreement, Skillsapien grants you a limited license to access and, if you are a Member, to use this Site internally for the purpose of ordering and receiving the Site Services available and authorised from this Site. You must not sell, reproduce, distribute, modify, display, publicly perform, prepare derivative works based on, repost or otherwise use any content of this Site in any way for any public or commercial purpose without prior written consent of Skillsapien or the rights holder. You must not use any content of this Site on any other Web site or in a networked computer environment for any purpose except your own internal viewing. You will not attempt to reverse engineer or attempt to interfere with the operation of any part of this Site unless expressly permitted by law. This Site or any portion of this Site may not be reproduced, duplicated, copied, sold, resold or otherwise exploited for any commercial purpose that is not expressly permitted by Skillsapien.</p>
        <p>Skillsapien and its licensors retain all of its right, title and interest in and to all patent rights, inventions, copyrights, know-how, and trade secrets relating to the Site. The Skillsapien logo and name are trademarks of Skillsapien, and may be registered in certain jurisdictions. All other product names, company names, marks, logos and symbols on the Site may be the trademarks of their respective owners.</p>
        <p>Except as expressly stated above, nothing in this Agreement confers any license under any of Skillsapien's or any third party's Intellectual Property Rights, whether by estoppel, implication or otherwise.</p>
        <h2>Resolution of Disputes Between Member and Skillsapien</h2>
        <p>If a dispute arises between you and Skillsapien, our goal is to resolve such dispute quickly and cost-effectively. Accordingly, you and Skillsapien agree that we will resolve any claim or controversy at law or equity that arises between us out of this Agreement or the Skillsapien Services (a “Claim”) in accordance with this section entitled“Resolution of Disputes Between Member and Skillsapien.” Before resorting to these alternatives, you agree to first contact Skillsapien directly to seek dispute assistance.</p>
        <h2>Term; Termination and Suspension</h2>
        <p>This Agreement shall become effective as your contractual agreement upon your acceptance or your use of the Site, and shall continue until your Account is terminated by Skillsapien or you as provided for under the terms of this Section.</p>
        <p>Unless otherwise agreed to in writing between the parties, either party may terminate the contractual agreement represented by this Agreement at any time upon notice to the other party. In the event you properly terminate the contractual agreement represented by this Agreement, your Account is automatically terminated and (i) Skillsapien shall continue to perform those Skillsapien Services necessary to complete any open transaction between you and another Member; and (ii) you shall continue to be obligated to pay any amounts accrued but unpaid as of the date of termination to Skillsapien for any Site Services and to any Candidates for any Candidate Services.</p>
        <p>Without limiting Skillsapien's other remedies, we may issue a warning, or temporarily suspend, indefinitely suspend or terminate your Account, and refuse to provide any or all Site Services to you if: (a) you breach the letter or spirit of any terms and conditions of this Agreement or the linked policies and information incorporated herein by reference, including our written policies and procedures posted on the Site; (b) we suspect or become aware that you have provided false or misleading information to us; or (c) we believe in our sole discretion that your actions may cause legal liability for you, our Members or for Skillsapien or are contrary to the interests of the Site or the Skillsapien user community. Once indefinitely suspended or terminated, you must not continue to use the Site under the same Account, a different Account, or reregister under a new Account.</p>
        <p>In addition, violations of this Agreement may be prosecuted to the fullest extent of the law and may result in additional penalties and sanctions.</p>
        <p>Without limiting Skillsapien's other remedies, to the extent you engage in actions or activities which circumvent the Skillsapien Site or otherwise reduce fees owed Skillsapien under this Agreement, you must pay Skillsapien for all fees owed to Skillsapien and reimburse Skillsapien for all losses and costs (including any and all Skillsapien employee time) and reasonable expenses (including attorney fees) related to investigating such breach and collecting such fees.</p>
        <p>Skillsapien reserves the right to terminate any User access, Account, or Job for any reason or no reason, at its sole discretion and to refuse to provide registration and membership to you in the future. We will notify you
if we cancel your membership, unless in our judgment giving notice would cause a risk of further violation or damages. However, we will notify you that your Account will be cancelled if the law requires such notification.</p>
        <p>When your Account is terminated for any reason, you may no longer have access to data, messages, files and other material you keep on the Site. The material may be deleted along with all your previous posts and proposals. This Agreement and all its sections will survive termination of the contractual agreement between us.</p>
        <h2>Notification of Skillsapien Members</h2>
        <p>You acknowledge and agree that the value, reputation and goodwill of the Site depend on transparency of Member Account status to all Members, including both yourself and other Members who are participating in Jobs with you. You therefore agree as follows: IF SKILLSAPIEN SUSPENDS OR TERMINATES YOUR ACCOUNT, SKILLSAPIEN HAS THE RIGHT BUT NOT THE OBLIGATION TO (1) NOTIFY OTHER MEMBERS ENGAGED IN ACTIVE JOBS WITH YOU TO INFORM THEM OF YOUR SUSPENDED OR TERMINATED ACCOUNT OR JOB STATUS, AND (2) PROVIDE THEM WITH SUMMARY REASONS FOR THE ACTION.</p>
        <h2>Disclaimers, Limitations and Exclusions</h2>
        <p>You are responsible for creation, storage, and backup of your business records. This Agreement and any registration for or subsequent use of the Site will not be construed as creating any responsibility on Skillsapien's part to store, backup, retain, or grant access to any information or data for any period.</p>
        <p>We have implemented commercially reasonable technical and organisational measures designed to secure your personal information from accidental loss and from unauthorised access, use, alteration or disclosure. However, we cannot guarantee that unauthorised third parties will never be able to defeat those measures or use your personal information for improper purposes. You acknowledge that you provide your personal information, or information about the entity that you represent, at your own risk.</p>
        <h2>WARRANTY DISCLAIMER</h2>
        <p>THE SITE SERVICES PROVIDED BY SKILLSAPIEN OR ANY OF OUR LICENSORS OR OUR THIRD-PARTY SERVICE PROVIDERS ARE PROVIDED "AS IS," AS AVAILABLE, AND WITHOUT ANY WARRANTIES OR CONDITIONS (EXPRESS OR IMPLIED, INCLUDING THE IMPLIED WARRANTIES OF MERCHANTABILITY, ACCURACY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON- INFRINGEMENT, ARISING BY STATUTE OR OTHERWISE IN LAW OR FROM A COURSE OF DEALING OR USAGE OR TRADE). WE MAKE NO REPRESENTATIONS OR WARRANTIES, OF ANY KIND, EITHER EXPRESS OR IMPLIED, AS TO THE QUALITY, IDENTITY OR RELIABILITY OF ANY THIRD PARTY, OR AS TO THE ACCURACY OF THE POSTINGS MADE ON THE WEB SITE BY ANY THIRD PARTY. SOME JURISDICTIONS DO NOT ALLOW FOR ALL THE FOREGOING LIMITATIONS ON IMPLIED WARRANTIES, SO TO THAT EXTENT, IF ANY, SOME OR ALL OF THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU.</p>
        <h2>LIMITATION OF LIABILITY</h2>
        <p>IN NO EVENT SHALL WE OR OUR LICENSORS OR OUR THIRD-PARTY SERVICE PROVIDERS BE LIABLE TO YOU OR ANY OTHER MEMBER FOR ANY SPECIAL, INDIRECT, CONSEQUENTIAL, INCIDENTAL OR PUNITIVE DAMAGES PURSUANT TO THIS AGREEMENT, INCLUDING BUT NOT LIMITED TO, LOSS OF PROFITS, LOSS OF BUSINESS OPPORTUNITIES OR LOSS OF GOODWILL, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
        <p>NOTWITHSTANDING ANY OTHER PROVISION OF THIS AGREEMENT, IN NO EVENT WILL OUR LIABILITY TO YOU FOR ANY ACTION OR CLAIM RELATED TO THE SITE SERVICES PROVIDED UNDER THIS AGREEMENT, WHETHER BASED ON CONTRACT, TORT, NEGLIGENCE OR ANY OTHER THEORY OF LIABILITY, EXCEED THE GREATER OF: (A) $100, OR (B) THE AGGREGATE AMOUNT OF SERVICE CHARGES ACTUALLY COLLECTED BY US FROM YOU FOR SITE SERVICES TO WHICH THE LIABILITY RELATES DURING THE SIX (6) MONTH PERIOD IMMEDIATELY PRECEDING THE DETERMINATION OF SUCH LIABILITY. SOME JURISDICTIONS DO NOT ALLOW FOR ALL THE FOREGOING EXCLUSIONS AND LIMITATIONS OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO TO THAT EXTENT, IF ANY, SOME OR ALL OF THESE LIMITATIONS AND EXCLUSIONS MAY NOT APPLY TO YOU.</p>
        <h2>Release</h2>
        <p>If you have a dispute with another Member, you release Skillsapien (and our officers, directors, agents, subsidiaries, joint ventures and employees) from claims, demands and damages (actual and consequential) of every kind and nature, known and unknown, arising out of or in any way connected with such dispute.</p>
        <p>This release will not apply if the cause of the dispute is Skillsapien’s failure to meet aSkillsapien obligation under the Terms of Service.</p>
        <h2>INDEMNITY</h2>
        <p>You agree to defend, hold harmless and indemnify Skillsapien from and against any and all losses, costs, expenses, damages or other liabilities incurred by Skillsapien arising from or related to any cause of action, claim, suit, proceeding, demand or action brought by a third party against Skillsapien: (a) in connection with your use of the Site Services including any payment obligations incurred through use of the Site Services; or (b) resulting from: (i) your use of the Site; (ii) your decision to supply credit information via the Site, including personal financial information; (iii) your decision to submit postings and accept offers from other Members; (iv) any breach of contract or other claims made by Members with which you conducted business through the Site; (v) your breach of any provision of this Agreement; (vi) any liability arising from the tax treatment of payments or any portion thereof; (vii) any negligent or intentional wrongdoing by any Member with which you conducted business through the Site; (viii) any act or omission of yours with respect to the payment of feesto any Candidate; (ix) your dispute of or failure to pay any invoice or any other payment; or (x) your obligations to a Candidate. Any such indemnification shall be conditioned on our: (a) notifying you in writing of any such claim, demand, action, cost, liability, loss or threat of any thereof; (b) cooperating with you in the defence or settlement thereof; and (c) allowing you to control such defence or settlement. We shall be entitled to participate in such defence through our own counsel at our own cost and expense. We reserve the right to report any wrongdoing of which we become aware to the applicable government agencies or otherwise.</p>
        <h2>Notices and Communications</h2>
        <p>Unless you otherwise indicate in writing to Customer Support, Skillsapien will communicate with you by email or by posting communications on the Site. You consent to receive communications from us electronically and you agree that these electronic communications satisfy any legal requirement that such communications be in writing. You will be considered to have received a communication when Skillsapien sends it to the email address you have provided to Skillsapien on the Site, or when Skillsapien posts such communication on the Site. You must keep your email address updated on this Site, and you must regularly check this Site for postings. If you fail to respond to an email message from Skillsapien regarding violation, dispute or complaint within two business days, Skillsapien has the right to terminate or suspend your account.</p>
        <h2>Miscellaneous Terms and Conditions</h2>
        <p>You are responsible for compliance with applicable local laws, keeping in mind that access to the contents of this Site may not be legal for or by certain persons or in certain countries. Skillsapien will not be considered to have modified or waived any of our rights or remedies under this Agreement unless the modification or waiver is in writing and signed by an authorised representative of Skillsapien. No delay or omission by Skillsapien in exercising its rights or remedies will impair its rights or be construed as a waiver. Any single or partial exercise of a right or remedy will not preclude further exercise of any other right or remedy.</p>
        <p>You will not transfer, assign or delegate your rights or obligations (including your Account) under this Agreement to anyone without the express written permission of Skillsapien, and any attempt to do so will be null and void. Skillsapien may assign this Agreement in its sole discretion.</p>
        <p>This Agreement, together with any other legal notices and agreements published by Skillsapien via the Site, shall constitute the entire agreement between you and Skillsapien concerning the Site. If any provision in this Agreement is deemed invalid by a court of competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of this Agreement, which shall remain in full force and effect.</p>
        <p>Except for the payment of fees to Skillsapien, neither of the parties to this Agreement shall be responsible for the failure to perform or any delay in performance of any obligation hereunder due to labour disturbances,accidents, fires, floods, telecommunications or Internet failures, strikes, wars, riots, rebellions, blockades, acts of government, governmental regulations or restrictions imposed by law or other similar conditions beyond the reasonable control of such party. The performance of such obligationsshall be extended by the length of such delay.</p>
        <p>This Agreement and all documents referenced in this Agreement (including the Terms of Service available by hyperlink above) comprise the entire agreement between you and Skillsapien with respect to the use of this Site and supersede all prior agreements between the parties regarding the subject matter contained herein as well as any conflicting or inconsistent terms in any Web site that link to or are linked from this Site. For convenience, this Agreement may be displayed in HTML and/or PDF versions. In the event of any inconsistency between such versions, the PDF version will govern.</p>
        <h2>Certain Defined Terms</h2>
        <p>Any term not otherwise defined in this Agreement will be used throughout this Agreement with the following definition:</p>
        <p>“Account” means the Skillsapien Account you open when you register to become a Member and use the Site Services.</p>
        <p>“Recruiter” means a Member that investigates and purchases Candidate Services or identifies a Candidate through the Site.</p>
        <p>“Candidate” means a Member that offers and delivers services or identifies a Recruiter through the Site.</p>
        <p>“Candidate Services” means all services delivered by Candidates.</p>
        <p>“Skillsapien Services” means the creation, hosting, maintenance, and provision of the Site and all services delivered by Skillsapien that are accessible through the Site. The term Skillsapien Services does not include Candidate Services or Third-Party Services.</p>
        <p>“Intellectual Property Rights” means all patent rights, copyright rights, mask work rights, moral rights, rights of publicity, trademark, trade dress and service mark rights, goodwill, trade secret rights and other intellectual property rights as may now exist or hereafter come into existence, and all applications therefore and registrations, renewals and extensions thereof, under the laws of any state, country, territory or other jurisdiction.</p>
        <p>“Member” means a person or legal entity that registers for an Account. “Member Contract” shall have the meaning given to it above. “Payment Service” means the Skillsapien Billing and Payment Service.</p>
        <p>“Secure Areas” means portions of the site that are encrypted using the Hypertext Transfer Protocol Secure (also known as “HTTPS”) or any other encryption mechanism.</p>
        <p>“Services Agreement” means the default Services Agreement Between Recruiter and Candidate and this default Services Agreement may be modified by Recruiter and Candidate as described.</p>
        <p>“Site Policies” means the Terms of Service and all obligations, requirements, and guidelines contained in or linked from the Site.</p>
        <p>“Site Services” means all services that are accessible through the Site except Candidate Services. “Third-Party Services” means all services that are accessible through the Site and delivered by third
parties. The term Third-Party Services does not include Skillsapien Services or Candidate Services.
</p>
        <p>“User” means (1) a person who is a Member, using the Site on his or her own behalf, or (2) a person who is using the Site on behalf of a Member that is a company or organisation.</p>
        <p>“Visitor” means a person who is only visiting the Site, not a Member or User.
“Workroom” means the place on the Site where a Recruiter and Candidate can communicate and worktogether on a Job.</p>
        <p>“You” means a Visitor or Member accessing the Site or using the Site Services on his or her own behalf; or, if the Site Services are used on behalf of a Member, "you" means the Member for which the Site Services are used and the User who accesses the Site on behalf of such Member (and such User represents that he or she has the authority to do so on the Member's behalf).</p>
        <h2>Contacting Us</h2>
        <p>If you wish to report a violation of the Terms of Service, have any questions or need assistance, please contact Skillsapien as follows:</p>
        <p>For Support and Online Help:	<a href="contact-us.php">Contact Us</a>!</p>
        <p>Email Customer Service:	<a href="#">customer.service@skillsapien.com</a></p>
        <p>For other technical support:	<a href="#">support@skillsapien.com</a></p>
        
      </div>
      <div class="center_right">
          <?php include('latest_news.php'); ?>
        <div class="social">
          <div class="social_top">
		  <h2>Follow us on:</h2>
          </div>
          <div class="social_di"> <a href="http://www.facebook.com/Skillsapien/"><img src="images/facebook.gif" alt="" /></a> <a href="http://www.linkedin.com/company/skillsapien/"><img src="images/link_in.gif" alt="" /></a> <a href="http://plus.google.com/107493995351899544917/"><img src="images/google_plus.jpg"  alt="" /><a href="http://twitter.com/Skillsapien/"><img src="images/twitter.gif" alt="" /></a>
            <div class="clear"></div>
          </div>
          <div class="clear"></div>
        </div>
      </div>
      <div class="clear"></div>
    </div>
    <div class="clear"></div>
  </div>
  <div class="clear"></div>
</div>
<div class="canten">
  <div class="clear"></div>
</div>

<!--Footer-->
<?php echo $get_template->process('global_footer.php')?>
</body>
</div></div>
</html>
